### ISSUE TITLE
An `exclude_files` entry matches too much

### ISSUE THREAD

**Issue by mamacdon** [cloudfoundry-incubator/buildpack-packager#5]
1. Create a `manifest.yml` containing an innocent-looking `exclude_files` entry:

  ```yaml
---
language: ruby

exclude_files:
- log/
```
2. Create a bunch of folders whose names end in 'log':

  ```console
$ mkdir log \
      && mkdir blog \
      && mkdir dialog
```
3. Run the packager.
4. The output zip is missing all 3 directories. 

I expected it to exclude **only** folders named `log`, not folders whose names have `log` as a suffix.

**Comment by flavorjones** [comment]
@mamacdon, thanks for reporting this. We'll take a look.

**Comment by jtarchie** [comment]
Thanks! We've made the fix in the latest version of buildpack-packager, v2.2.1.  Closing now.

**Comment by flavorjones** [comment]
@jtarchie should we close?

**Comment by mamacdon** [comment]
Awesome, thanks for the quick response.

**Comment by flavorjones** [comment]
@jtarchie should we close?

**Comment by flavorjones** [comment]
Verified fix, closing.
